`NameError`が発生する